/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WordsIndexRouteImport } from './routes/words/index'
import { Route as WordsWordRouteImport } from './routes/words/$word'
import { Route as StagesStageIdPlayRouteImport } from './routes/stages.$stageId.play'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WordsIndexRoute = WordsIndexRouteImport.update({
  id: '/words/',
  path: '/words/',
  getParentRoute: () => rootRouteImport,
} as any)
const WordsWordRoute = WordsWordRouteImport.update({
  id: '/words/$word',
  path: '/words/$word',
  getParentRoute: () => rootRouteImport,
} as any)
const StagesStageIdPlayRoute = StagesStageIdPlayRouteImport.update({
  id: '/stages/$stageId/play',
  path: '/stages/$stageId/play',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/words/$word': typeof WordsWordRoute
  '/words/': typeof WordsIndexRoute
  '/stages/$stageId/play': typeof StagesStageIdPlayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/words/$word': typeof WordsWordRoute
  '/words': typeof WordsIndexRoute
  '/stages/$stageId/play': typeof StagesStageIdPlayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/words/$word': typeof WordsWordRoute
  '/words/': typeof WordsIndexRoute
  '/stages/$stageId/play': typeof StagesStageIdPlayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/words/$word' | '/words/' | '/stages/$stageId/play'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/words/$word' | '/words' | '/stages/$stageId/play'
  id: '__root__' | '/' | '/words/$word' | '/words/' | '/stages/$stageId/play'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WordsWordRoute: typeof WordsWordRoute
  WordsIndexRoute: typeof WordsIndexRoute
  StagesStageIdPlayRoute: typeof StagesStageIdPlayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/words/': {
      id: '/words/'
      path: '/words'
      fullPath: '/words/'
      preLoaderRoute: typeof WordsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/words/$word': {
      id: '/words/$word'
      path: '/words/$word'
      fullPath: '/words/$word'
      preLoaderRoute: typeof WordsWordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stages/$stageId/play': {
      id: '/stages/$stageId/play'
      path: '/stages/$stageId/play'
      fullPath: '/stages/$stageId/play'
      preLoaderRoute: typeof StagesStageIdPlayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WordsWordRoute: WordsWordRoute,
  WordsIndexRoute: WordsIndexRoute,
  StagesStageIdPlayRoute: StagesStageIdPlayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
