/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WordsRouteImport } from './routes/words'
import { Route as StoreRouteImport } from './routes/store'
import { Route as AvatarRouteImport } from './routes/avatar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StagesIndexRouteImport } from './routes/stages.index'
import { Route as StagesStageIdIndexRouteImport } from './routes/stages.$stageId.index'
import { Route as StagesStageIdModeRouteImport } from './routes/stages.$stageId.$mode'

const WordsRoute = WordsRouteImport.update({
  id: '/words',
  path: '/words',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const AvatarRoute = AvatarRouteImport.update({
  id: '/avatar',
  path: '/avatar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StagesIndexRoute = StagesIndexRouteImport.update({
  id: '/stages/',
  path: '/stages/',
  getParentRoute: () => rootRouteImport,
} as any)
const StagesStageIdIndexRoute = StagesStageIdIndexRouteImport.update({
  id: '/stages/$stageId/',
  path: '/stages/$stageId/',
  getParentRoute: () => rootRouteImport,
} as any)
const StagesStageIdModeRoute = StagesStageIdModeRouteImport.update({
  id: '/stages/$stageId/$mode',
  path: '/stages/$stageId/$mode',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/avatar': typeof AvatarRoute
  '/store': typeof StoreRoute
  '/words': typeof WordsRoute
  '/stages/': typeof StagesIndexRoute
  '/stages/$stageId/$mode': typeof StagesStageIdModeRoute
  '/stages/$stageId/': typeof StagesStageIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/avatar': typeof AvatarRoute
  '/store': typeof StoreRoute
  '/words': typeof WordsRoute
  '/stages': typeof StagesIndexRoute
  '/stages/$stageId/$mode': typeof StagesStageIdModeRoute
  '/stages/$stageId': typeof StagesStageIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/avatar': typeof AvatarRoute
  '/store': typeof StoreRoute
  '/words': typeof WordsRoute
  '/stages/': typeof StagesIndexRoute
  '/stages/$stageId/$mode': typeof StagesStageIdModeRoute
  '/stages/$stageId/': typeof StagesStageIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/avatar'
    | '/store'
    | '/words'
    | '/stages/'
    | '/stages/$stageId/$mode'
    | '/stages/$stageId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/avatar'
    | '/store'
    | '/words'
    | '/stages'
    | '/stages/$stageId/$mode'
    | '/stages/$stageId'
  id:
    | '__root__'
    | '/'
    | '/avatar'
    | '/store'
    | '/words'
    | '/stages/'
    | '/stages/$stageId/$mode'
    | '/stages/$stageId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AvatarRoute: typeof AvatarRoute
  StoreRoute: typeof StoreRoute
  WordsRoute: typeof WordsRoute
  StagesIndexRoute: typeof StagesIndexRoute
  StagesStageIdModeRoute: typeof StagesStageIdModeRoute
  StagesStageIdIndexRoute: typeof StagesStageIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/words': {
      id: '/words'
      path: '/words'
      fullPath: '/words'
      preLoaderRoute: typeof WordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avatar': {
      id: '/avatar'
      path: '/avatar'
      fullPath: '/avatar'
      preLoaderRoute: typeof AvatarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stages/': {
      id: '/stages/'
      path: '/stages'
      fullPath: '/stages/'
      preLoaderRoute: typeof StagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stages/$stageId/': {
      id: '/stages/$stageId/'
      path: '/stages/$stageId'
      fullPath: '/stages/$stageId/'
      preLoaderRoute: typeof StagesStageIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stages/$stageId/$mode': {
      id: '/stages/$stageId/$mode'
      path: '/stages/$stageId/$mode'
      fullPath: '/stages/$stageId/$mode'
      preLoaderRoute: typeof StagesStageIdModeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AvatarRoute: AvatarRoute,
  StoreRoute: StoreRoute,
  WordsRoute: WordsRoute,
  StagesIndexRoute: StagesIndexRoute,
  StagesStageIdModeRoute: StagesStageIdModeRoute,
  StagesStageIdIndexRoute: StagesStageIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
